name: image_assorter
description: Assort images as you like
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: ^1.0.2
  file_selector_platform_interface: ^2.0.2
  file_selector_windows: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_linux: ^0.0.2
  flutter_simple_treeview: ^3.0.0-nullsafety.1
  json_annotation: ^4.0.1
  path_provider: ^2.0.1
  resizable_widget: ^1.0.4
  simple_property_observer: ^1.0.1
  sqflite: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  simple_property_observer_builder: ^1.0.1

flutter:
  uses-material-design: true
